### ISSUE TITLE
[Fix] Docker環境の再構築

### ISSUE THREAD

**Issue by takeshi-arihori** [takeshi-arihori/movie-api#28]
# 🐳 Docker環境の再構築

## 概要
issue #11で作成されるはずだったDocker関連ファイルが不足しているため、開発環境の構築ができない状態です。

## 不足しているファイル
- [ ] `backend/Dockerfile` - Go API用Dockerファイル
- [ ] `frontend/Dockerfile` - React用Dockerファイル  
- [ ] `compose.yaml` - Docker Compose設定
- [ ] `Makefile` - 開発コマンド集

### backend/Dockerfile
```dockerfile
FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/main .
CMD ["./main"]
```

### compose.yaml
```yaml
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
```

## 完了条件
- [ ] Docker Composeで全サービスが起動する
- [ ] バックエンドAPIが正常にアクセス可能
- [ ] データベース接続が正常に動作
- [ ] Makefileコマンドが動作

## 優先度
🟡 Medium - 開発環境構築に必要

## 関連Issue
- #11 (基盤構築)
- #12 (設定管理)
